### ISSUE TITLE
error msg="Not found info"

### ISSUE THREAD

**Issue by mkj28** [jtblin/aws-mock-metadata#12]
How would I go about debugging:
```
time="2018-10-14T07:33:42Z" level=info msg="Requesting /latest/meta-data/instance-id"
time="2018-10-14T07:33:42Z" level=info msg="Requesting /latest/meta-data/iam/info"
time="2018-10-14T07:33:42Z" level=error msg="Not found info"
```

running in minikube with:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aws-mock
  labels:
    app: aws-mock
spec:
  selector:
    matchLabels:
      app: aws-mock
  template:
    metadata:
      name: aws-mock
      labels:
        app: aws-mock
    spec:
      containers:
      - image: jtblin/aws-mock-metadata
        imagePullPolicy: Always
        name: aws-mock
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: AVAILABILITY_ZONE
          value: "us-west-2"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_SESSION_TOKEN
        - name: AWS_SDK_LOAD_CONFIG
          value: "1"
        args:
          - "--availability-zone=us-west-2"
          - "--instance-id=i-0a148cec064fc841c"
          - "--app-port=80"
          - "--private-ip=172.28.159.34"
```
